import re
import json
import urllib.request, urllib.parse, urllib.error
from tornado.escape import xhtml_escape

OEMBED_HINTS = {
        'youtube.com': 'http://www.youtube.com/oembed?url=%s&format=json',
        'flickr.com/photos': 'http://flickr.com/services/oembed.json?url=%s&maxwidth=800&maxheight=600',
        'http://vimeo.com/': 'http://vimeo.com/api/oembed.json?url=%s&maxwidth=800&maxheight=600',
        'www.amazon.co': 'http://oohembed.com/oohembed/?url=%s&maxwidth=400&maxheight=300',
        'play.spotify.com/track/': 'https://embed.spotify.com/oembed/?url=%s',
        }

_URL_RE = re.compile(r"""\b((?:([\w-]+):(/{1,3})|www[.])(?:(?:(?:[^\s&()]|&amp;|&quot;)*(?:[^!"#$%&'()*+,.:;<=>?@\[\]^`{|}~\s]))|(?:\((?:[^\s&()]|&amp;|&quot;)*\)))+)""")

SMILEYS = {':(': 'Crying face.png',
 ':)': 'Smiley.png',
 ':*': 'Kiss.png',
 '(wink)': 'Winking smiley.png',
 '(handshake)': 'Handshake.png',
 '(muscle)': 'Muscle.png',
 ':#': 'My lips are sealed.png',
 '(F)': 'Flower.png',
 'I=)': 'Sleepy.png',
 ':?': 'Thinking.png',
 '(devil)': 'Devil.png',
 '(d)': 'Drink.png',
 '(h)': 'Heart.png',
 'B=)': 'Cool smiley.png',
 '\\o/': 'Dancing.png',
 '(envy)': 'Envy.png',
 ':=s': 'Worried.png',
 '(talk)': 'Talking.png',
 'B-)': 'Cool smiley.png',
 '(dull)': 'Dull.png',
 ']:)': 'Evil grin.png',
 '(laugh)': 'Big smiley.png',
 '(N)': 'No.png',
 '&gt;:)': 'Evil grin.png',
 '(rock)': 'Rock.png',
 '(mooning)': 'Mooning.png',
 '(yawn)': 'Yawn.png',
 '($)': 'Cash.png',
 '(drink)': 'Drink.png',
 '\\:D/': 'Dancing.png',
 ':o': 'Surprised smiley.png',
 '(rofl)': 'Rolling on the floor laughing.png',
 ':d': 'Big smiley.png',
 'B=|': 'Nerdy.png',
 '(brokenheart)': 'Broken heart.png',
 ':|': 'Speechless smiley.png',
 '(ninja)': 'Ninja.png',
 ':x': 'My lips are sealed.png',
 '(wasntme)': "It wasn't me!.png",
 '(happy)': 'Happy.png',
 ':&amp;': 'Puking.png',
 ':p': 'Smiley with tongue out.png',
 '(H)': 'Heart.png',
 '|(': 'Dull.png',
 ':s': 'Worried.png',
 '(clock)': 'Time.png',
 ':O': 'Surprised smiley.png',
 ':D': 'Big smiley.png',
 '(grin)': 'Evil grin.png',
 '(no)': 'No.png',
 ':@': 'Angry.png',
'B)': 'Cool smiley.png',
'(emo)': 'Emo.png',
'(cake)': 'Cake.png',
':X': 'My lips are sealed.png',
'(pi)': 'Pizza.png',
'(y)': 'Yes.png',
'(hug)': 'Hug.png',
'(london)': 'Raining.png',
':P': 'Smiley with tongue out.png',
'(mmm)': 'Mmmmm....png',
'B-|': 'Nerdy.png',
':S': 'Worried.png',
'8=|': 'Nerdy.png',
':=x': 'My lips are sealed.png',
'8)': 'Cool smiley.png',
'X-(': 'Angry.png',
':-O': 'Surprised smiley.png',
':=|': 'Speechless smiley.png',
'I-)': 'Sleepy.png',
'(Y)': 'Yes.png',
':-@': 'Angry.png',
':-D': 'Big smiley.png',
':-X': 'My lips are sealed.png',
':=o': 'Surprised smiley.png',
':-S': 'Worried.png',
':-P': 'Smiley with tongue out.png',
':-&amp;': 'Puking.png',
':=d': 'Big smiley.png',
':=X': 'My lips are sealed.png',
'(ss)': 'Skype.png',
':-o': 'Surprised smiley.png',
'(doh)': 'Doh!.png',
'(flex)': 'Muscle.png',
':=S': 'Worried.png',
':=P': 'Smiley with tongue out.png',
':-d': 'Big smiley.png',
'(mo)': 'Cash.png',
'8-|': 'Nerdy.png',
':-x': 'My lips are sealed.png',
':=O': 'Surprised smiley.png',
':-|': 'Speechless smiley.png',
':"&gt;': 'Blush.png',
':-s': 'Worried.png',
':=@': 'Angry.png',
'(L)': 'Heart.png',
':=D': 'Big smiley.png',
'(mp)': 'Phone.png',
'(chuckle)': 'Giggle.png',
'|-()': 'Yawn.png',
':=?': 'Thinking.png',
':-p': 'Smiley with tongue out.png',
'(fubar)': 'FUBAR.png',
'(blush)': 'Blush.png',
'(punch)': 'Punch.png',
':=&amp;': 'Puking.png',
':=*': 'Kiss.png',
':=(': 'Crying face.png',
':=)': 'Smiley.png',
'8=)': 'Cool smiley.png',
'8|': 'Nerdy.png',
':=#': 'My lips are sealed.png',
';)': 'Winking smiley.png',
';(': 'Crying face.png',
':=$': 'Blush.png',
':-*': 'Kiss.png',
'\\:d/': 'Dancing.png',
':-(': 'Crying face.png',
':-)': 'Smiley.png',
'8-)': 'Cool smiley.png',
'(ok)': 'Yes.png',
':-#': 'My lips are sealed.png',
'(st)': 'Raining.png',
':-$': 'Blush.png',
'(yes)': 'Yes.png',
'X=(': 'Angry.png',
':-?': 'Thinking.png',
'(love)': 'Heart.png',
'(clap)': 'Clapping.png',
'(sad)': 'Sad face.png',
'(swear)': 'Swearing.png',
'(nod)': 'Nodding.png',
'(cash)': 'Cash.png',
'(puke)': 'Puking.png',
'(inlove)': 'In love.png',
'(shake)': 'Shake.png',
'(movie)': 'Movie.png',
'x=(': 'Angry.png',
'(music)': 'Music.png',
'(wait)': 'Wait.png',
'(bear)': 'Hug.png',
'(o)': 'Time.png',
'(kate)': 'Make-up.png',
'(sun)': 'Sun.png',
'X(': 'Angry.png',
'(bandit)': 'Bandit.png',
'x-(': 'Angry.png',
'(dance)': 'Dancing.png',
'(party)': 'Party.png',
'|=(': 'Dull.png',
'(smoking)': 'Smoking.png',
':$': 'Blush.png',
'(worry)': 'Worried.png',
'(:|': 'Sweating.png',
':=p': 'Smiley with tongue out.png',
'(think)': 'Thinking.png',
'(drunk)': 'Drunk.png',
'x(': 'Angry.png',
'(flower)': 'Flower.png',
'(heart)': 'Heart.png',
'(tongueout)': 'Smiley with tongue out.png',
';=)': 'Winking smiley.png',
';=(': 'Crying face.png',
'B|': 'Nerdy.png',
'(smirk)': 'Smirking.png',
'(snooze)': 'Sleepy.png',
'(m)': 'You have mail.png',
'(cool)': 'Cool smiley.png',
'(film)': 'Movie.png',
'(hrv)': 'Pool party.png',
'(*)': 'Star.png',
'(time)': 'Time.png',
'(smoke)': 'Smoking.png',
'|-(': 'Dull.png',
'|-)': 'Sleepy.png',
'(hi)': 'Hi.png',
'(bug)': 'Bug.png',
'(mail)': 'You have mail.png',
'(whew)': 'Whew.png',
'(beer)': 'Beer.png',
':^)': 'Wondering.png',
'(ph)': 'Phone.png',
'(makeup)': 'Make-up.png',
'(toivo)': 'Toivo.png',
'(l)': 'Heart.png',
'(rain)': 'Raining.png',
'(mm)': 'Mmmmm....png',
'(cry)': 'Crying face.png',
'(D)': 'Drink.png',
'(ci)': 'Smoking.png',
'(poolparty)': 'Pool party.png',
'(mmmm)': 'Mmmmm....png',
'(call)': 'Call.png',
'(headbang)': 'Banging head on wall.png',
'(giggle)': 'Giggle.png',
'(finger)': 'Finger.png',
'(pizza)': 'Pizza.png',
'(sweat)': 'Sweating.png',
'(~)': 'Movie.png',
'(angry)': 'Angry.png',
'(nerd)': 'Nerdy.png',
'(e)': 'You have mail.png',
';-)': 'Winking smiley.png',
';-(': 'Crying face.png',
'(kiss)': 'Kiss.png',
'(wonder)': 'Wondering.png',
'(speechless)': 'Speechless smiley.png',
'(u)': 'Broken heart.png',
'(bow)': 'Bowing.png',
'(coffee)': 'Coffee.png',
'(banghead)': 'Banging head on wall.png',
'(^)': 'Cake.png',
'(O)': 'Time.png',
'(tmi)': 'Too much information.png',
'(star)': 'Star.png',
'(surprised)': 'Surprised smiley.png',
'(skype)': 'Skype.png',
'(smile)': 'Smiley.png',
'(n)': 'No.png',
'(U)': 'Broken heart.png',
'(f)': 'Flower.png',
'(phone)': 'Phone.png',
'(angel)': 'Angel.png'}

def message_beautify(body):
    words = body.split(" ")
    final_words = []
    for word in words:
        escape_required = False

        # beautify links
        if _URL_RE.search(word):
            # transform image links
            if any(word.endswith(x) for x in ['.jpg','.png','.gif']):
                word = "<img src='%s'>" % word
                escape_required = False

            # expand possible oembeds
            for hint in OEMBED_HINTS.keys():
                if hint in word:
                    oembed_fd = urllib.request.urlopen(OEMBED_HINTS[hint] % body)
                    raw_resp = oembed_fd.read().decode("utf8")
                    oembed_resp = json.loads(raw_resp)
                    if 'html' in oembed_resp:
                        word = oembed_resp['html']
                        escape_required = False
                    else:
                        if oembed_resp['type'] == "photo":
                            word = "<img src='%s'>" % oembed_resp['url']
                            escape_required = False

            if escape_required:
                word = "<a href='%s'>%s</a>" % (word, word)
                escape_required = False

        # expand smileys
        smiley = SMILEYS.get(word, None)
        if smiley:
            word = "<img src='/static/emoticons/%s'/>" % smiley
            escape_required = False

        if escape_required:
            word = xhtml_escape(word)

        final_words.append(word)

    return ' '.join(final_words)
